### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by viktor-yakubiv** [turchak/memory-pair-game#2]
Eslint — is the powerful tool which at the beginning of your amazing front-end career helps you to avoid a lot of mistakes. Also, eslint allows you to share code style between team members. It's quite cool, isn't it?

I suggest to start with most strict configuration — [Airbnb JavaScript Guide](https://github.com/airbnb/javascript)

**Comment by turchak** [comment]
Thanks! It's true Esling - useful tool for beginners!
